### ISSUE TITLE
Issue with Smiley compilation script (most likely some libraries problem)

### ISSUE THREAD

**Issue by fn0v0tny** [sam-kirby/bsc#1]
Hi Sam,
I'm a new plasma physics BSc project student at Imperial who is tasked with using the pic ml and is not very proficient with using C++/MPI/parallel computing.
However, I am having trouble with compiling both smilei and smilei_sub on HPC.
I've set up a new environment, installed mpi4py and h5py using pip and GCC using conda.

However, conda environment contains doesn't contain the c++ libraries and based on tricks from stackowerflow I've set the LD_LIBRARY_PATH to /anaconda3/lib and the LD_PRELOAD to /lib64/libpthread.so.0 and /lib64/libc.so.6 to get rid of some of the errors 

=> 
this resulted in the compilation finishing (however the smilei won't run) and with an error of 
"mpicxx: symbol lookup error: /lib64/libm.so.6: undefined symbol: __strtold_nan, version GLIBC_PRIVATE"
 Does this suggest the libraries I am using are not the right ones for mpich?
GDB suggests installing some libraries using debug-info, which is not possible for non-root users...
Do you have any suggestions on what should I do to fix it?
Thank you in advance.
Filip

**Comment by sam-kirby** [comment]
I'll preface this by saying that I no longer have access to HPC and so can't test anything on that specific environment.

I think your error is telling you that you're trying to dynamically link to two components of glibc from two different versions. This is probably down to how you've setup the LD_LIBRARY_PATH and LD_PRELOAD variables. Are you setting these for compilation and running?

What exactly have you set LD_LIBRARY_PATH to? I'm assuming that you didn't mean to set it to the root anaconda directory and instead meant the one in your home? Have you overridden all other values or just prepended/appended?

In theory, there should be no need to:
1) Install gcc from conda
2) Set any variables that control the dynamic linker for compilation - the script tells the compiler which libraries to build against
3) Trample over the dynamic linker's config to such a degree; when running smilei you do need to append your conda lib folder - but only so that the correct version of Python can be found - [see here for an example](https://github.com/sam-kirby/pic-ml/blob/main/jobs/chirped_laser_ml/chirped_laser_ml.pbs#L23)

You also mentioned MPICH. At least last year, Imperial's HPC was using Intel's MPI library not MPICH. This is the reason for using pip to install it; that way it compiles it and links against the system's MPI library. Conda would otherwise pull a prebuilt binary linked against mpich. You have to have loaded the relevant module (module load mpi) before installing mpi4py. You may also need to load the gcc module, I can't remember.

Similar applies to h5py, make sure you load the relevant module before pip installing it to make sure it's built against the same library you'll be using later: module load hdf5/1.10.5-parallel (version may have changed).

**Comment by sam-kirby** [comment]
I've built Smilei_sub locally and everything still seems to work; I think that narrows it down to the environment on HPC. Honestly, about 60% of the time I spent on the project last year was on working round weird issues that I could only find on HPC like this and the 2048 simulations bug.

**Comment by sam-kirby** [comment]
I'd be interested to know what issues you ran into without modifying the job files?

**Comment by fn0v0tny** [comment]
Without modification I get "'libpython3.9.so.1.0: cannot open shared object file: No such file or directory"
I fixed this by providing the path to the libpython/ I could possibly download it from conda forge...

**Comment by sam-kirby** [comment]
To resolve that, you should just need to set:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib`

**Comment by fn0v0tny** [comment]
Thank you - now the smilei seems to run (based on reinstalling the environment with all modules preloaded), however when I run the simple demo(this one specifically https://github.com/SmileiPIC/Smilei/blob/master/benchmarks/tst1d_00_em_propagation.py)

It returns with an error and quite a few warnings
![image](https://user-images.githubusercontent.com/8459180/140538141-28a86a45-ec47-4262-a3f5-348594d19b85.png)

Thank you once again for your help :)
Filip

**Comment by sam-kirby** [comment]
You are attempting to run Smilei on the login node, which use fairly old CPUs.

However, if you used the job script to compile it, you compiled it targetting the newer CPUs present in the compute machine that ran the job.

SIGILL (Illegal Instruction) is the direct result of this. It's probably trying to use an AVX2 instruction.

You can use `lscpu` to dump the features of the CPU you are currently using and compare to the CPU of a compute node.

You can compile a generalised build of Smilei by removing `machine=linux_x86_64_gnu` from the make instruction. This will produce a build targetting an old pentium processor, and will be significantly slower.

You should avoid running Smilei on the login nodes as it's very resource intensive and will annoy the other users of HPC.

**Comment by joratto** [comment]
Hi Sam,

I'm Filip's project partner and I'm getting the following error when running compile_smilei_sub.pbs :
```
Loading anaconda3/personal
  Loading requirement: fix_unwritable_tmp fix_setxattr
/usr/libexec/git-core/git-remote-https: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```
Filip does not have this problem when he submits the same job. Any advice?

**Comment by sam-kirby** [comment]
Is your output here only the stderr? If so, what is the stdout?

Have you changed the job at all?

It looks like you have an issue with Git, have you done anything that might explain that?

**Comment by sam-kirby** [comment]
It’s worth pointing out you don’t need to use my job scripts to compile Smilei.

If you want to use my ml-supervisor, then you only strictly need to make the following change, which you can do manually:

```diff
diff --git a/src/SmileiMPI/SmileiMPI.cpp b/src/SmileiMPI/SmileiMPI.cpp
index f04caa25a..760020d48 100755
--- a/src/SmileiMPI/SmileiMPI.cpp
+++ b/src/SmileiMPI/SmileiMPI.cpp
@@ -78,6 +78,16 @@ SmileiMPI::~SmileiMPI()
 {
     delete[]periods_;
 
+    MPI_Comm controller;
+    MPI_Comm_get_parent(&controller);
+
+    if (controller != MPI_COMM_NULL) {
+        MPI_Request req;
+        MPI_Ibarrier(controller, &req);
+        MPI_Wait(&req, MPI_STATUS_IGNORE);
+        MPI_Comm_disconnect(&controller);
+    }
+
     MPI_Finalize();
 
 } // END SmileiMPI::~SmileiMPI
 ```

The rest of the changes allow the use of Python 3 in the name list and allow you to add an analysis function to the name list. These are useful changes, but not essential.

**Comment by joratto** [comment]
> Is your output here only the stderr? If so, what is the stdout?

Yes. stdout is simply:
`pulling with rebase...`

The job ought to be unchanged, and I don't know of any changes I might've made to git that would explain this.

**Comment by sam-kirby** [comment]
Okay, well it's definitely a problem with how you have Git or the dynamic linker setup. Your version of Git was compiled against a different version of OpenSSH than is in your environment. If you've messed with your `LD_LIBRARY_PATH` that could cause this, or if you've taken a Git binary from another system.

If memory serves correctly, there is module for a newer version of Git available on HPC which you could try to load.

The compilation script does not touch the dynamic linker configuration and makes minimal assumptions about Git.

It's not reaching the point it tries to compile Smilei. It would print `building...` to stdout before trying to.

It's not necessary for you to pull and rebase if the upstream Smilei repo hasn't changed. If the patches applied successfully (you can check using `git log`) then you can remove that command from the script.

**Comment by sam-kirby** [comment]
As far as I can tell, there is no action required of me. Please reach out if you encounter issues in the software I have written.

**Comment by fn0v0tny** [comment]
Hi,
sorry to bother you again, I managed to compile the smilei using the scripts provided and put it in the PATH environmental variable. However in parallel when running density_ml.pbs on a density_ml_a.py namelist, the smilei_sub doesn't produce any output files (even though the output says that the process finished successfully and the output files were created). The temp folders are empty and the whole main.py process fails with 

FileNotFoundError: [Errno 2] No such file or directory: '/rds/general/ephemeral/user/fn319/ephemeral/density_ml_best1bin_152/tmph0jghh82/result

When I checked the result folder it is actually empty and I wasn't able to find the files anywhere else in my repository.
When running the smilei_sub alone it does produce the output files. 
Do you have any idea what might cause this kind of issue.?
Thank you in advance.
Filip

**Comment by sam-kirby** [comment]
You seem not to have read or understood what the namelist is doing.

Smilei's raw results are not stored on $EPHEMERAL when using this namelist. I did this to get around a synchronisation issue or rate limit that would cause Smilei to crash when writing large amounts of data from multiple processes to the networked store. They instead write to a local (to the node) temporary directory that is lost on job termination. The `result` file is all that is put on $EPHEMERAL as this allows data exchange between the nodes. See here: https://github.com/sam-kirby/pic-ml/blob/main/namelists/density_a_ml.py#L48-L49

Without the logs it's difficult to tell you why the result is not being stored. I have a few ideas, but I'd prefer not to guess.

**Comment by fn0v0tny** [comment]
Which logs do you want?
[density_ml.pbs.o4817212.txt](https://github.com/sam-kirby/pic-ml/files/7538922/density_ml.pbs.o4817212.txt)
[debug.log](https://github.com/sam-kirby/pic-ml/files/7538942/debug.log)
[main.log](https://github.com/sam-kirby/pic-ml/files/7538943/main.log)
Thank you once again
Filip

**Comment by fn0v0tny** [comment]
Ok, I figured out that it was because I haven't specified the goal function, but even after specifying it, happi is not able to load the data as I get the 
"WARNING: `/rds/general/ephemeral/user/fn319/ephemeral/density_ml_best1bin_DE_solver/tmpeybc9l50` does not point to any valid Smilei simulation path
No valid paths to Smilei simulation results have been provided"
And the whole optimization fails with AttributeError: 'SmileiSimulation' object has no attribute 'ParticleBinning'

Here are the logs.
[density_ml.pbs.e4825192.txt](https://github.com/sam-kirby/pic-ml/files/7540409/density_ml.pbs.e4825192.txt)
[density_ml.pbs.o4825192.txt](https://github.com/sam-kirby/pic-ml/files/7540410/density_ml.pbs.o4825192.txt)
[main.log](https://github.com/sam-kirby/pic-ml/files/7540411/main.log)
[debug.log](https://github.com/sam-kirby/pic-ml/files/7540412/debug.log)

Thank you in advance.
Filip

**Comment by sam-kirby** [comment]
How did you compile Smilei? Based on your log, Smilei's version is `4230c58-master` which aligns with the latest commit to the upstream repo. This seems to suggest that none of the patches have been applied using Git.

Did you manually apply any of the patches? What is the output of `git status`, `git log --oneline` and `git diff` in the directory you built Smilei from?

> I figured out that it was because I haven't specified the goal function

Not quite the issue. Smilei is not running the analysis function from the namelist (https://github.com/sam-kirby/pic-ml/blob/main/namelists/density_a_ml.py#L51-L56). The patch to do so is missing, otherwise the end of each Smilei run's logs would have an "Analysis" section that looks like one of the below options:

![image](https://user-images.githubusercontent.com/23245543/141826578-234f28cf-bce4-4fe8-8695-a3d4b83b406b.png)

![image](https://user-images.githubusercontent.com/23245543/141826697-f14d647a-1685-45da-9004-96b1a149d36d.png)

**Comment by sam-kirby** [comment]
For comparison, your Smilei logs end without the "Analysis" section:

![image](https://user-images.githubusercontent.com/23245543/141827989-e4fafaac-346d-4fcf-a040-616a9e0d29f6.png)

**Comment by sam-kirby** [comment]
As an aside, if you want to use the goal functions that don't rely on Smilei doing the analysis for you there are a couple of things to consider:

1) You can't use the `TMPDIR` on HPC as scratch space - all results must go to shared space (i.e. `EPHEMERAL`). This is because `TMPDIR` is not shared between nodes, and the results must be accessible to the node on which the supervisor is running. You therefore need to modify the namelist.
2) Reading and writing to `EPHEMERAL` from multiple nodes was unreliable (or at least it was a few months ago). This will cause crashes.
3) This approach is slower as performing the analysis on the supervisor's task will bottleneck the number Smilei tasks that can be started.

**Comment by fn0v0tny** [comment]
OK, I managed to run the density_ml. However, after the first generation, it produces the following MPI error. As I am not that experienced with MPI, I have no idea how to properly debug it/solve the error. I've tried setting the environmental variable FI_PROVIDER to tcp and loading the newer version of MPI and intel_suite(or not using the intel suite at all) as suggested by smilei tips at http://imperiallaserplasma.pbworks.com/w/page/116786172/smieli_tips
I tried to start the resume script, which managed to calculate the next generation, after which it failed with the same error. Is there some more sensible solution to the problem, than developing a script, which runs the resume script again each time after it fails?
Here are the logs.
[density_ml.pbs.e4844236.txt](https://github.com/sam-kirby/pic-ml/files/7605491/density_ml.pbs.e4844236.txt)
[debug.log](https://github.com/sam-kirby/pic-ml/files/7605492/debug.log)
[main.log](https://github.com/sam-kirby/pic-ml/files/7605493/main.log)
[density_ml.pbs.o4844236.txt](https://github.com/sam-kirby/pic-ml/files/7605494/density_ml.pbs.o4844236.txt)
Thank you, once again.
Filip

**Comment by sam-kirby** [comment]
I don't believe I ever encountered this error and unfortunately I'm not sure what you can do about it. The hint on the wiki to use IMPI 2020 looks good, but to make it work you would probably have to recompile mpi4py with the new module loaded - did you do this?

> developing a script, which runs the resume script again each time after it fails

You can use PBS to queue jobs to run after another has finished or crashed. The following snippet is similar to what I used to queue up a couple of days worth of progress on an optimisation in one go. This uses `afterok` which means it only continues if there isn't a crash. See the following link for more information: https://arc.umich.edu/pbs-job-dependencies/

```sh
JOB=$(qsub ../density_ml.pbs)

for i in {1..5}
do
  JOB=$(qsub -W depend=afterok:$JOB ../density_ml_cont.pbs
done
```

**Comment by sam-kirby** [comment]
It's worth noting that it's not crashing at the change of generation but some time after - a number of simulations in the new generation successfully run and get analysed before the crash.

To try to narrow down where the issue is you could try:
1. Shrinking the size of the population (by at least half) to see if in these circumstances you can complete more than 1 generation at a time.
2. Counting the number of simulations until a crash occurs.
